### ISSUE TITLE
Translate it to Japanese

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/awesome-canvas#12]

**Comment by CodeGenki** [comment]
Hey, I might be able to help here! Would it be cool if I tried to work on this?

**Comment by raphamorim** [comment]
Yup! It would be amazing @CodeGenki <3

I'm thinking about translation organization:
```
- translations
   - JAPANESE.md
   - KOREAN.md
- LICENSE
- README.MD
```

Then in `README.md` add a link to all available translations.
What do you think?

**Comment by CodeGenki** [comment]
Alright, sounds good!
