### ISSUE TITLE
ZIM - JavaScript Canvas Framework to Code Creativity!

### ISSUE THREAD

**Issue by danzen** [raphamorim/awesome-canvas#29]
A little late to the repository, perhaps... but could you please add ZIM at https://zimjs.com - ZIM is a JavaScript Canvas Framework with many conveniences, components and controls - and probably amounts to one of the top 5 canvas endeavors.  Would do a pull request but there is still one there from 2016 ;-).  Cheers.

**Comment by raphamorim** [comment]
Hey @danzen, that sounds as a good idea. Would you mind send a PR?

**Comment by raphamorim** [comment]
Closed by #32

**Comment by danzen** [comment]
Just added a pull request - sorry for the delay!

**Comment by danzen** [comment]
Just checking on the pull request - hope you are around and Happy holidays!
