### ISSUE TITLE
Some websites fromraphamorim.com cannot open

### ISSUE THREAD

**Issue by jerrybendy** [raphamorim/awesome-canvas#8]
Hi, 

There is some examples which from `fromraphamorim.com` such as `Cloth Effect`, `Colorful Particles` cannot open. It shows the domain is on sale.

Thanks for your share, it's really awesome! 😁

**Comment by raphamorim** [comment]
Whoa!
Thank you for that, I really forgot to change it.
Fixed  in 3d13952

**Comment by jerrybendy** [comment]
OK, Thank you
